### ISSUE TITLE
服务获取到的 tags 数据不全

### ISSUE THREAD

**Issue by xiaohuoni** [chenshuai2144/umi-plugin-repo#3]
根据 ui ，需要展示的有 title，date， branches，tar 等
但是服务（ `type: 'org.umi-plugin-repo.tags'` ）返回的数据只有 `["v0.1.0", "v0.1.1", "v0.1.2"]`

**Comment by chenshuai2144** [comment]
只要本地的 tag 就行了，删除功能也没必要做。

**Comment by xiaohuoni** [comment]
问题是数据只有  `["v0.1.0", "v0.1.1", "v0.1.2"]` 这点数据展示来，没任何信息。
